/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bottom-bun.glb 
*/

import { useGLTF } from "@react-three/drei";

function BottomBun(props) {
  const { nodes, materials } = useGLTF("/models/bottom-bun.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.337, 1.02, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Circle004_burger_0.geometry}
          material={materials.burger}
          position={[0, 0, 7.441]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/bottom-bun.glb");
export default BottomBun;
