/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cheese.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Cheese(props) {
  const { nodes, materials } = useGLTF("/models/cheese.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane001_burger_0.geometry}
        material={materials.burger}
        position={[0.337, 0.21, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/cheese.glb");

export default Cheese;
