/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 onion.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useCylinder } from "@react-three/cannon";

function Onion(props) {
  const { nodes, materials } = useGLTF("/models/onion.glb");

  const [ref] = useCylinder(() => ({
    mass: 0.02, // ~20g – thin onion ring
    args: [0.42, 0.42, 0.06, 16],
    position: props.position ?? [0, 0, 0],
    rotation: props.rotation ?? [0, 0, 0],
    material: { friction: 0.4, restitution: 0.25 },
    linearDamping: 0.5,
    angularDamping: 0.6,
    sleepSpeedLimit: 0.1, // body sleeps when nearly stopped
    sleepTimeLimit: 0.5, // seconds before it sleeps
    ...props.physicsProps,
  }));

  return (
    <group {...props} dispose={null} ref={ref}>
      <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh
          geometry={nodes.Cylinder010_burger_0.geometry}
          material={materials.burger}
          position={[0, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/onion.glb");

export default Onion;
