/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 onion.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Onion(props) {
  const { nodes, materials } = useGLTF("/models/onion.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.098, 0.135, 0.126]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Cylinder010_burger_0.geometry}
          material={materials.burger}
          position={[-0.937, 0.937, 1.469]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/onion.glb");

export default Onion;
