/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 patty.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Patty(props) {
  const { nodes, materials } = useGLTF("/models/patty.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.337, -1.547, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Circle005_burger_0.geometry}
          material={materials.burger}
          position={[-1.433, -1.433, 31.357]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/patty.glb");

export default Patty;
