/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 patty.glb 
*/

// import React from "react";
// import { useGLTF } from "@react-three/drei";
// import { useCylinder } from "@react-three/cannon";

// function Patty(props) {
//   const { nodes, materials } = useGLTF("/models/patty.glb");

//   const [ref] = useCylinder(() => ({
//     mass: 0.18,
//     args: [1, 1, 0.22, 24],
//     position: props.position ?? [0, 0, 0],
//     rotation: props.rotation ?? [0, 0, 0],
//     material: { friction: 0.8, restitution: 0.05 },
//     linearDamping: 0.5,
//     angularDamping: 0.9,
//     sleepSpeedLimit: 0.1, // body sleeps when nearly stopped
//     sleepTimeLimit: 0.5, // seconds before it sleeps
//     ...props.physicsProps,
//   }));

//   return (
//     <group {...props} dispose={null} ref={ref}>
//       <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
//         <mesh
//           geometry={nodes.Circle005_burger_0.geometry}
//           material={materials.burger}
//           position={[0, 0, 0]}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload("/models/patty.glb");

// export default Patty;
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 patty.glb 
*/

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 patty.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useCylinder } from "@react-three/cannon";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

function Patty(props) {
  const { nodes, materials } = useGLTF("/models/patty.glb");

  // ─── Physics body ──────────────────────────────────────────────────────────
  // Heavier, high friction, very low restitution — firm meat patty feel
  const [ref, api] = useCylinder(() => ({
    mass: 0.18,
    args: [1, 1, 0.22, 24],
    position: props.position ?? [0, 0, 0],
    rotation: props.rotation ?? [0, 0, 0],
    material: { friction: 0.85, restitution: 0.06 },
    linearDamping: 0.65, // heavy drag — settles fast
    angularDamping: 0.92, // resists spinning
    sleepSpeedLimit: 0.1,
    sleepTimeLimit: 0.5,
    ...props.physicsProps,
  }));

  // ─── Live physics state ────────────────────────────────────────────────────
  const velocityRef = useRef(new THREE.Vector3());
  const angVelocityRef = useRef(new THREE.Vector3());

  useEffect(() => {
    const u1 = api.velocity.subscribe((v) =>
      velocityRef.current.set(v[0], v[1], v[2]),
    );
    const u2 = api.angularVelocity.subscribe((v) =>
      angVelocityRef.current.set(v[0], v[1], v[2]),
    );
    return () => {
      u1();
      u2();
    };
  }, [api.velocity, api.angularVelocity]);

  // ─── Visual deformation ref ────────────────────────────────────────────────
  const meshGroupRef = useRef();

  // Spring banks — very stiff, heavily damped = firm feel
  const springY = useRef({ v: 1, dv: 0 }); // squash Y
  const bendX = useRef({ v: 0, dv: 0 }); // tilt along X
  const bendZ = useRef({ v: 0, dv: 0 }); // tilt along Z

  const STIFF = 55; // very stiff spring — snaps back immediately
  const DAMP = 9.0; // heavy damping — almost no oscillation
  const BEND_S = 0.03; // minimal bend drive — barely tilts
  const SQ_S = 0.08; // minimal squash on impact

  useFrame((_, delta) => {
    if (!meshGroupRef.current) return;

    const vel = velocityRef.current;
    const speed = vel.length();

    // Y squash — very subtle, stiff meat doesn't compress much
    const targetY = 1 - Math.min(speed * SQ_S, 0.08);
    stepSpring(springY.current, targetY, STIFF, DAMP, delta);

    // Slight tilt in direction of motion — like a sliding puck, not a floppy slice
    const targetBX = -vel.x * BEND_S;
    const targetBZ = -vel.z * BEND_S;
    stepSpring(bendX.current, targetBX, STIFF * 0.8, DAMP * 0.8, delta);
    stepSpring(bendZ.current, targetBZ, STIFF * 0.8, DAMP * 0.8, delta);

    const scaleY = Math.max(0.88, springY.current.v);
    const scaleXZ = 1 + (1 - scaleY) * 0.15; // minimal volume preserve

    meshGroupRef.current.scale.set(scaleXZ, scaleY, scaleXZ);

    // Slight rotation tilt — stiff so kept very small
    meshGroupRef.current.rotation.x = bendZ.current.v * 0.12;
    meshGroupRef.current.rotation.z = bendX.current.v * 0.12;
  });

  return (
    <group {...props} dispose={null} ref={ref}>
      <group
        // ref={meshGroupRef}
        position={[0, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Circle005_burger_0.geometry}
          material={materials.burger}
          position={[0, 0, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
          ref={meshGroupRef}
        />
      </group>
    </group>
  );
}

// ─── Spring stepper ────────────────────────────────────────────────────────
function stepSpring(spring, target, stiffness, damping, dt) {
  const disp = spring.v - target;
  const acc = -stiffness * disp - damping * spring.dv;
  spring.dv += acc * dt;
  spring.v += spring.dv * dt;
}

useGLTF.preload("/models/patty.glb");

export default Patty;
