/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pickle.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Pickle(props) {
  const { nodes, materials } = useGLTF("/models/pickle.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.071, 0.26, 0.046]}
        rotation={[-Math.PI / 2, 0, -2.599]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Cylinder011_burger_0.geometry}
          material={materials.burger}
          position={[1.149, 0.373, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/pickle.glb");

export default Pickle;
