/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 tomato.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Tomato(props) {
  const { nodes, materials } = useGLTF("/models/tomato.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder008_burger_0.geometry}
        material={materials.burger}
        position={[0.337, 0.14, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      />
    </group>
  );
}

useGLTF.preload("/models/tomato.glb");

export default Tomato;
