/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 top-bun.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function TopBun(props) {
  const { nodes, materials } = useGLTF("/models/top-bun.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.337, -6.624, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Circle007_burger_0.geometry}
          material={materials.burger}
          position={[0, 0, 94.643]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/top-bun.glb");

export default TopBun;
